version: '3.9'

services:
  myportfolio:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./myportfolio:/myportfolio
      - ./data/web:/vol/web
    environment:   #replace these
      - SECRET_KEY=4ly6@m64mi57l4abvo1_4in_i0jpmcdk71k06^7snm$p_*@w7= 
      - DEBUG=1
      - DB_HOST=host
      - DB_NAME=dev
      - DB_USER=YOUR_USER
      - DB_PASS=YOUR_PASS
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=YOUR_USER
      - POSTGRES_PASSWORD=YOUR_PASS